### ISSUE TITLE
Duplicate rules when configMap value is RuleGroups or RuleGroup

### ISSUE THREAD

**Issue by leojonathanoh** [Nordstrom/prometheusRuleLoader#12]
A `configMap` like:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-rules
  namespace: default
  annotations:
    prometheus.io/rules: "true"
data:
  myrulegroups: |
    groups:
    - name: my.rules
      rules:
      - alert: Watchdog
        expr: vector(1)
        labels:
        severity: none
        annotations:
          message: |
            This is an alert meant to ensure that the entire alerting pipeline is functional.
            This alert is always firing, therefore it should always be firing in Alertmanager
            and always fire against a receiver. There are integrations with various notification
            mechanisms that send a notification when this alert is not firing. For example the
            "DeadMansSnitch" integration in PagerDuty.
```

results in two duplicate rules in the generated rules file:

```
$ cat /etc/prometheus/dynamic-rules/rules.yml
groups:
- name: my.rules
  rules:
  - alert: Watchdog
    expr: vector(1)
    annotations:
      message: |
        This is an alert meant to ensure that the entire alerting pipeline is functional.
        This alert is always firing, therefore it should always be firing in Alertmanager
        and always fire against a receiver. There are integrations with various notification
        mechanisms that send a notification when this alert is not firing. For example the
        "DeadMansSnitch" integration in PagerDuty
- name: my.rules
  rules:
  - alert: Watchdog
    expr: vector(1)
    annotations:
      message: |
        This is an alert meant to ensure that the entire alerting pipeline is functional.
        This alert is always firing, therefore it should always be firing in Alertmanager
        and always fire against a receiver. There are integrations with various notification
        mechanisms that send a notification when this alert is not firing. For example the
        "DeadMansSnitch" integration in PagerDuty
```

As a result, `prometheusRuleLoader` reload of prometheus fails with prometheus throwing an error:

```
2019/07/25 01:47:59 Unable to reload the Prometheus config. Endpoint: http://127.0.0.1:9090/-/reload, Reponse StatusCode: 500, Response Body: failed to reload config: one or more errors occurred while applying the new configuration (--config.file="/etc/prometheus/prometheus.yml")
```
